version: '3.9'

services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: marketplace.settings
      MYSQL_HOST: db
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - backend_media:/app/media

  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  db_data:
  backend_media:
